### PR TITLE
[bugfix] Prevent destroy operation for static ports in bulk list when…

### LINKED ISSUE #270: `mso_schema_site_anp_epg_bulk_staticport` resource destroys/recreates object instead of updating
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v.1.5.6

### MSO version

* V 4.1.2

### APIC version and APIC Platform for Site Level Resources

* N/A

### Affected Resource(s)

* mso_schema_site_anp_epg_bulk_staticport

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
```
module.tf-aci-ndo-staticports.mso_schema_site_anp_epg_bulk_staticport.accessPortsL2_bulk["TENANT-0100-EPG-prod-aci"] must be replaced
Plan: 47 to add, 5 to change, 47 to destroy.
```

### Expected Behavior
The resource should update the object in NDO by adding/removing the ports. Not completely destroy and re-create the object.
Destroying and recreating the object creates a time period where any error on the pipeline can leave an incomplete template on NDO.

### Actual Behavior
Terraform is destroying and re-creating all objects

### Steps to Reproduce
Terraform plan/apply

### References

* #0000

### PR DESCRIPTION
**Pull request by akinross**
… updating the list

fixes #270

### CODE REVIEW

**Review by anvitha-jain — APPROVED** [review]

**Review by shrsr — APPROVED** [review]
LGTM

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by lhercot — APPROVED** [review]
LGTM

**Comment by edudppaz** [comment]
Hi @akinross . The issue itself seems to be fixed as now the resource is updated-in-place instead of destroyed-recreating. But adding a new port to the list now re-orders the list, showing an update to every single entry on the bulk. Im guessing this is due to some sort() or ordering of the data when being written to the state.
It technically doesnt affect the resource being applied, but it would be nice to get the "real" change instead of a re-ordering of all paths:

```
  # module.tf-aci-ndo-staticports.mso_schema_site_anp_epg_bulk_staticport.accessPortsL2_bulk["TENANT-server-03-EPG-ACI"] will be updated in-place
  ~ resource "mso_schema_site_anp_epg_bulk_staticport" "accessPortsL2_bulk" {
        id            = "/site//template/Strchd-L2-Template/anp/server-AP/epg/server-03-EPG"
        # (5 unchanged attributes hidden)

      ~ static_ports {
          ~ path                 = "eth1/3" -> "eth1/20"
            # (8 unchanged attributes hidden)
        }
      ~ static_ports {
          ~ path                 = "eth1/4" -> "eth1/3"
            # (8 unchanged attributes hidden)
        }
      ~ static_ports {
          ~ path                 = "eth1/5" -> "eth1/4"
            # (8 unchanged attributes hidden)
        }
      ~ static_ports {
          ~ path                 = "eth1/6" -> "eth1/5"
            # (8 unchanged attributes hidden)
        }
      ~ static_ports {
          ~ path                 = "eth1/7" -> "eth1/6"
            # (8 unchanged attributes hidden)
        }
      ~ static_ports {
          ~ path                 = "eth1/8" -> "eth1/7"
            # (8 unchanged attributes hidden)
        }
      ~ static_ports {
          ~ path                 = "eth1/9" -> "eth1/8"
            # (8 unchanged attributes hidden)
        }
      + static_ports {
          + deployment_immediacy = "lazy"
          + leaf                 = "1001"
          + micro_seg_vlan       = 0
          + mode                 = "regular"
          + path                 = "eth1/9"
          + path_type            = "port"
          + pod                  = "pod-1"
          + vlan                 = 2002
        }
```

On this output, the new port in the configuration is the 1/20. **The 1/9 is already configured**, but due to the re-ordering on the state, is being shown as a new one.

**Comment by shrsr** [comment]
@edudppaz Akini is on leave and will be back soon!

The reason you are seeing this behaviour is because **static_ports** is defined as **TypeList** in the resource which makes Terraform treat **static_ports** as ordered collections. This means that the order of items in a list is significant and any change in the order of items is considered a change to the list itself. 

A way to get around this would be to use **TypeSet** for the said attribute but it comes with its own cosmetic quirks.

**Pull request merged**
