### PR TITLE
[minor_change] Add support for site aware policy enforcement mode in …

### LINKED ISSUE #272: Add support for site aware policy enforcement under vrf
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add the attribute to enable Site Aware Policy Enforcement Mode to mso_schema_template_vrf

### New or Affected Resource(s) + MSO Class(es):

* mso_schema_template_vrf+ siteAwarePolicyEnforcementMode

### MSO version

* V 4.2.3

### APIC version and APIC Platform for Site level Resources

* V 5.2 and on-prem/cloud-aws/cloud-azure/all.

### Potential Terraform Configuration

```hcl
site_aware_policy_enforcement = true
```

### PR DESCRIPTION
**Pull request by akinross**
…schema_template_vrf

fixes #272

### CODE REVIEW

**Comment by akinross** [comment]
Need to update mod and vendor files still, depending on mso-go-client PR https://github.com/ciscoecosystem/mso-go-client/pull/134.

**Review by samiib — CHANGES_REQUESTED** [review]
Is it possible to add tests for this resource & datasource? 

Had a discussion with @akinross and won't need tests here for now.

**Review by samiib — APPROVED** [review]
LGTM

**Review by anvitha-jain — APPROVED** [review]

**Review by shrsr — APPROVED** [review]
LGTM

**Review by lhercot — APPROVED** [review]
LGTM

**Pull request merged**
