### PR TITLE
[minor_change] Bump required go version to go v1.21 (DCNE-216)

### PR DESCRIPTION
**Pull request by akinross**

### CODE REVIEW

**Review by samiib — APPROVED** [review]
LGTM

Do you have any concerns about the vendor file changes? It appears to build though.

**Comment by akinross** [comment]
> LGTM
> 
> Do you have any concerns about the vendor file changes? It appears to build though.

What do you mean concerns about vendor files?

**Review by shrsr — APPROVED** [review]
LGTM

**Comment by samiib** [comment]
> > LGTM
> > Do you have any concerns about the vendor file changes? It appears to build though.
> 
> What do you mean concerns about vendor files?

@akinross I was mostly wondering why so many got removed. I think it could be a dependency optimisation in newer versions of Go. Dependencies that are not direct dependencies are indirect so it appears to be de-duplicating them. 👍

**Review by gmicol — APPROVED** [review]
LGTM

**Pull request merged**
