### PR TITLE
fix import for anp_epg_static_leaf to include template (DCNE-214)

### PR DESCRIPTION
**Pull request by juchowan**

### CODE REVIEW

**Review by akinross — APPROVED** [review]
LGTM

**Review by anvitha-jain — APPROVED** [review]
LGTM

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by shrsr — APPROVED** [review]
LGTM

**Review by samiib — APPROVED** [review]
LGTM

**Review by lhercot — APPROVED** [review]
LGTM

**Comment by lhercot** [comment]
Thanks for your contribution!

**Pull request merged**
